In [192]:
import pandas as pd
import numpy as np

In [193]:
cctv = pd.read_csv('서울시CCTV설치운영현황(자치구)_년도별_210731기준.csv',
                    skiprows=1, encoding='euc-kr')
cctv.head()

,구분,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
0,계,"77,032","7,667","2,200","3,491","4,439","6,582","8,129","9,947","9,876","11,961","11,132","1,608"
1,종로구,"1,772",813,0,0,210,150,1,261,85,9,200,43
2,중 구,"2,333",16,114,87,77,236,240,372,386,155,361,289
3,용산구,"2,383",34,71,234,125,221,298,351,125,307,617,0
4,성동구,"3,602",448,125,212,105,339,310,874,390,262,461,76

In [194]:
cctv.rename(columns={'구분' : '구별'}, inplace=True)
cctv.rename(columns={'총계':'CCTV대수'}, inplace=True)
cctv.loc[cctv.구별=='계', '구별'] = '합계'
for column in cctv.columns[1:]:
    cctv[column] = cctv[column].str.replace(',', '').astype(int)
cctv.구별 = cctv.구별.apply(lambda x : x.replace(' ',''))
cctv.head()
cctv_2017 = cctv[['2012년 이전', '2012년','2012년','2013년','2014년','2015년','2016년','2017년']].sum(axis=1)
cctv_recent = cctv[['2018년', '2019년', '2020년']].sum(axis=1)
cctv['최근증가율(%)'] = round((cctv_recent / cctv_2017) * 100).astype(int)
cctv.drop(columns=['2012년 이전', '2012년','2012년','2013년','2014년','2015년','2016년','2017년','2018년', '2019년', '2020년', '2021년'], inplace=True)
cctv

      구별  CCTV대수  최근증가율(%)
0     합계   77032        74
1    종로구    1772        20
2     중구    2333        72
3    용산구    2383        75
4    성동구    3602        44
5    광진구    2588       107
6   동대문구    2497        32
7    중랑구    3296       187
8    성북구    3958        91
9    강북구    2462       447
10   도봉구    1629        80
11   노원구    2415        62
12   은평구    3791       118
13  서대문구    2940        44
14   마포구    2421        84
15   양천구    3312        27
16   강서구    2560        72
17   구로구    4075        45
18   금천구    2374       149
19  영등포구    3778        98
20   동작구    2297        82
21   관악구    4942        47
22   서초구    3704        47
23   강남구    6502        60
24   송파구    2854       190
25   강동구    2547       110

In [195]:
cctv.shape

(26, 3)

In [209]:
df = pd.read_csv('서울시주민등록인구(구별)통계.txt', sep='\t', skiprows=1)
df = df.drop(index=[0,1], axis=0)
df

,기간,자치구,세대,합계,합계.1,합계.2,한국인,한국인.1,한국인.2,등록외국인,등록외국인.1,등록외국인.2,세대당인구,65세이상고령자
2,2021.2/4,종로구,"73,525","155,106","75,009","80,097","146,029","70,985","75,044","9,077","4,024","5,053",1.99,"27,605"
3,2021.2/4,중구,"62,897","132,259","64,526","67,733","123,016","60,019","62,997","9,243","4,507","4,736",1.96,"23,980"
4,2021.2/4,용산구,"111,650","240,665","116,858","123,807","226,378","108,948","117,430","14,287","7,910","6,377",2.03,"38,884"
5,2021.2/4,성동구,"134,542","295,767","143,927","151,840","289,162","141,042","148,120","6,605","2,885","3,720",2.15,"45,591"
6,2021.2/4,광진구,"166,957","355,306","170,624","184,682","342,481","165,233","177,248","12,825","5,391","7,434",2.05,"50,815"
7,2021.2/4,동대문구,"166,372","352,259","172,865","179,394","338,040","167,335","170,705","14,219","5,530","8,689",2.03,"61,262"
8,2021.2/4,중랑구,"185,073","394,679","194,556","200,123","389,972","192,688","197,284","4,707","1,868","2,839",2.11,"70,172"
9,2021.2/4,성북구,"194,364","443,206","212,849","230,357","433,658","209,210","224,448","9,548","3,639","5,909",2.23,"73,568"
10,2021.2/4,강북구,"144,525","306,093","148,824","157,269","302,645","147,542","155,103","3,448","1,282","2,166",2.09,"63,383"
11,2021.2/4,도봉구,"138,387","322,419","156,843","165,576","320,365","156,080","164,285","2,054",763,"1,291",2.31,"62,894"
12,2021.2/4,노원구,"217,322","520,005","250,532","269,473","515,997","248,719","267,278","4,008","1,813","2,195",2.37,"86,697"
13,2021.2/4,은평구,"213,662","479,409","229,241","250,168","475,371","227,584","247,787","4,038","1,657","2,381",2.22,"85,921"
14,2021.2/4,서대문구,"143,226","317,699","150,608","167,091","307,070","146,844","160,226","10,629","3,764","6,865",2.14,"53,627"
15,2021.2/4,마포구,"178,625","379,984","177,998","201,986","370,132","174,200","195,932","9,852","3,798","6,054",2.07,"53,891"
16,2021.2/4,양천구,"181,012","454,288","222,538","231,750","450,992","221,140","229,852","3,296","1,398","1,898",2.49,"66,942"
17,2021.2/4,강서구,"269,276","582,995","280,822","302,173","577,519","278,360","299,159","5,476","2,462","3,014",2.14,"90,404"
18,2021.2/4,구로구,"180,258","424,582","210,936","213,646","399,266","197,034","202,232","25,316","13,902","11,414",2.21,"71,186"
19,2021.2/4,금천구,"115,358","244,685","124,394","120,291","230,168","116,491","113,677","14,517","7,903","6,614",2,"40,181"
20,2021.2/4,영등포구,"185,025","402,375","199,881","202,494","377,421","186,482","190,939","24,954","13,399","11,555",2.04,"61,571"
21,2021.2/4,동작구,"183,859","397,231","191,657","205,574","387,847","187,617","200,230","9,384","4,040","5,344",2.11,"65,732"
22,2021.2/4,관악구,"274,565","502,698","251,713","250,985","488,800","245,404","243,396","13,898","6,309","7,589",1.78,"78,647"
23,2021.2/4,서초구,"171,574","422,174","202,027","220,147","418,407","200,163","218,244","3,767","1,864","1,903",2.44,"60,395"
24,2021.2/4,강남구,"232,707","536,107","256,449","279,658","531,375","254,139","277,236","4,732","2,310","2,422",2.28,"76,184"
25,2021.2/4,송파구,"280,707","664,341","320,113","344,228","658,670","317,531","341,139","5,671","2,582","3,089",2.35,"95,164"
26,2021.2/4,강동구,"200,170","469,094","230,388","238,706","465,209","228,652","236,557","3,885","1,736","2,149",2.32,"72,275"

In [197]:
#df['외국인비율'] = df['인구.6'] / df['인구']
#df.drop(columns=[1, 2], inplace=True, axis=0)
df.drop(columns=['기간','세대','합계.1','합계.2','한국인','한국인.1','한국인.2','등록외국인.1','등록외국인.2','세대당인구'],inplace=True)
for column in df.columns[1:]:
    df[column] = df[column].str.replace(',', '').astype(int)
df.rename(columns={'자치구' : '구별'}, inplace=True)
df.rename(columns={'합계' : '인구수'}, inplace=True)
df.rename(columns={'등록외국인' : '외국인'}, inplace=True)
df.rename(columns={'65세이상고령자' : '고령자'}, inplace=True)
df.head()

    구별      인구수     외국인      고령자
1   합계  9795426  229436  1576971
3   중구   132259    9243    23980
4  용산구   240665   14287    38884
5  성동구   295767    6605    45591
6  광진구   355306   12825    50815

In [198]:
df.shape

(25, 4)

In [199]:
df2 = pd.merge(cctv, df, how='inner')

In [200]:
df2.set_index('구별',inplace=True)
df2

      CCTV대수  최근증가율(%)      인구수     외국인      고령자
구별
합계     77032        74  9795426  229436  1576971
중구      2333        72   132259    9243    23980
용산구     2383        75   240665   14287    38884
성동구     3602        44   295767    6605    45591
광진구     2588       107   355306   12825    50815
동대문구    2497        32   352259   14219    61262
중랑구     3296       187   394679    4707    70172
성북구     3958        91   443206    9548    73568
강북구     2462       447   306093    3448    63383
도봉구     1629        80   322419    2054    62894
노원구     2415        62   520005    4008    86697
은평구     3791       118   479409    4038    85921
서대문구    2940        44   317699   10629    53627
마포구     2421        84   379984    9852    53891
양천구     3312        27   454288    3296    66942
강서구     2560        72   582995    5476    90404
구로구     4075        45   424582   25316    71186
금천구     2374       149   244685   14517    40181
영등포구    3778        98   402375   24954    61571
동작구     2297        82   397231    9384    65732
관악구     4942        47   502698   13898    78647
서초구     3704        47   422174    3767    60395
강남구     6502        60   536107    4732    76184
송파구     2854       190   664341    5671    95164
강동구     2547       110   469094    3885    72275

In [204]:
total_pop = df2[['인구수']].sum(axis=1)
pop_fore = df2[['외국인']].sum(axis=1)
pop_old = df2[['고령자']].sum(axis=1)

In [205]:
df2['외국인비율(%)'] = (pop_fore / total_pop) * 100
df2['고령자비율(%)'] = (pop_old / total_pop) * 100

In [206]:
df2

      CCTV대수  최근증가율(%)      인구수     외국인      고령자  외국인비율(%)   고령자비율(%)
구별
합계     77032        74  9795426  229436  1576971  2.342277  16.099055
중구      2333        72   132259    9243    23980  6.988560  18.131091
용산구     2383        75   240665   14287    38884  5.936468  16.156899
성동구     3602        44   295767    6605    45591  2.233177  15.414499
광진구     2588       107   355306   12825    50815  3.609565  14.301757
동대문구    2497        32   352259   14219    61262  4.036519  17.391181
중랑구     3296       187   394679    4707    70172  1.192615  17.779512
성북구     3958        91   443206    9548    73568  2.154303  16.599053
강북구     2462       447   306093    3448    63383  1.126455  20.707105
도봉구     1629        80   322419    2054    62894  0.637059  19.506915
노원구     2415        62   520005    4008    86697  0.770762  16.672340
은평구     3791       118   479409    4038    85921  0.842287  17.922275
서대문구    2940        44   317699   10629    53627  3.345620  16.879814
마포구     2421        84   379984    9852    53891  2.592741  14.182439
양천구     3312        27   454288    3296    66942  0.725531  14.735586
강서구     2560        72   582995    5476    90404  0.939288  15.506823
구로구     4075        45   424582   25316    71186  5.962570  16.766137
금천구     2374       149   244685   14517    40181  5.932934  16.421522
영등포구    3778        98   402375   24954    61571  6.201678  15.301895
동작구     2297        82   397231    9384    65732  2.362353  16.547550
관악구     4942        47   502698   13898    78647  2.764682  15.644980
서초구     3704        47   422174    3767    60395  0.892286  14.305713
강남구     6502        60   536107    4732    76184  0.882660  14.210596
송파구     2854       190   664341    5671    95164  0.853628  14.324571
강동구     2547       110   469094    3885    72275  0.828192  15.407360